// scripts/generate-wallets.ts
//
// Generates buyer + seller EVM keypairs and writes them to .env.local.
//
// What this script does (and does not do):
// - Generates two fresh random 256-bit private keys via viem.
// - Derives their Ethereum addresses.
// - Writes BUYER_PRIVATE_KEY, BUYER_ADDRESS, SELLER_PRIVATE_KEY, SELLER_ADDRESS
//   into .env.local, preserving any other existing lines.
// - Never overwrites existing non-empty wallet entries unless --force is passed.
// - Never prints private keys to stdout.
// - Writes .env.local with 0o600 mode where the OS supports it (no-op on Windows).
//
// This is a local, deterministic utility. No RPC calls. No Circle API. No
// fallbacks. If the file system or viem fails, the script exits non-zero.
//
// Usage:
//   npx tsx scripts/generate-wallets.ts            # refuses if wallets already exist
//   npx tsx scripts/generate-wallets.ts --force    # overwrites even if present
//
// After running this, the next step is to fund the buyer address at
// https://faucet.circle.com/ and then run scripts/deposit-to-gateway.ts.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';

const FORCE = process.argv.includes('--force');
const ENV_FILE = resolve(process.cwd(), '.env.local');
const WALLET_KEYS = [
  'BUYER_PRIVATE_KEY',
  'BUYER_ADDRESS',
  'SELLER_PRIVATE_KEY',
  'SELLER_ADDRESS',
] as const;

// --- Step 1: read existing .env.local (if any) -----------------------------

let existingLines: string[] = [];
const existing: Record<string, string> = {};

if (existsSync(ENV_FILE)) {
  existingLines = readFileSync(ENV_FILE, 'utf-8').split('\n');
  for (const line of existingLines) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) existing[m[1]] = m[2];
  }
}

const hasExistingWallets = WALLET_KEYS.some(
  (k) => existing[k] && existing[k].trim().length > 10,
);

if (hasExistingWallets && !FORCE) {
  console.error('❌ .env.local already contains wallet entries. Refusing to overwrite.');
  console.error('');
  console.error('   If you are sure you want new keys, run with --force.');
  console.error('   WARNING: regenerating keys abandons any funded balances on the old addresses.');
  console.error('            Withdraw or transfer USDC first.');
  process.exit(1);
}

// --- Step 2: generate new keypairs -----------------------------------------

const buyerPk = generatePrivateKey();
const sellerPk = generatePrivateKey();
const buyerAddress = privateKeyToAccount(buyerPk).address;
const sellerAddress = privateKeyToAccount(sellerPk).address;

// --- Step 3: upsert into .env.local, preserve other lines ------------------

function upsert(lines: string[], key: string, value: string): string[] {
  let found = false;
  const next = lines.map((line) => {
    if (line.startsWith(`${key}=`)) {
      found = true;
      return `${key}=${value}`;
    }
    return line;
  });
  if (!found) next.push(`${key}=${value}`);
  return next;
}

let updated = existingLines.length > 0 ? [...existingLines] : [
  '# Generated by scripts/generate-wallets.ts',
  '# Copy additional keys from .env.example as needed.',
  '',
];

updated = upsert(updated, 'BUYER_PRIVATE_KEY', buyerPk);
updated = upsert(updated, 'BUYER_ADDRESS', buyerAddress);
updated = upsert(updated, 'SELLER_PRIVATE_KEY', sellerPk);
updated = upsert(updated, 'SELLER_ADDRESS', sellerAddress);

if (updated.length === 0 || updated[updated.length - 1] !== '') {
  updated.push('');
}

writeFileSync(ENV_FILE, updated.join('\n'), { mode: 0o600 });

// --- Step 4: report (public info only) -------------------------------------

console.log('━'.repeat(70));
console.log('✅ Wallets generated and written to .env.local');
console.log('━'.repeat(70));
console.log(`  Buyer address:   ${buyerAddress}`);
console.log(`  Seller address:  ${sellerAddress}`);
console.log('');
console.log('  Private keys written to .env.local (mode 0600 where supported).');
console.log('  They are NOT printed to stdout.');
console.log('');
console.log('Next steps:');
console.log('');
console.log('  1. Fund the buyer with Arc testnet USDC:');
console.log('     → https://faucet.circle.com/');
console.log(`     → Paste this address:  ${buyerAddress}`);
console.log(`     → (Arc testnet gives 20 USDC per 2 hours per address.)`);
console.log('');
console.log('  2. Make sure .env.local has these other values set:');
console.log('     CIRCLE_API_KEY, ANTHROPIC_API_KEY, GEMINI_API_KEY');
console.log('     (see .env.example for the full list)');
console.log('');
console.log('  3. Deposit into your Gateway balance:');
console.log('     npx tsx scripts/deposit-to-gateway.ts 5');
console.log('━'.repeat(70));
